services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: app
    volumes:
      - ./backend:/var/www/html:cached
      - vendor_data:/var/www/html/vendor
      - storage_data:/var/www/html/storage
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: bets
      DB_USERNAME: user
      DB_PASSWORD: pass
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:8
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bets
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./backend:/var/www/html:cached
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app-network

volumes:
  db_data:
  vendor_data:
  storage_data:

networks:
  app-network:
    driver: bridge
