services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: app
    volumes:
      - ./backend:/var/www/html:cached
      - vendor_data:/var/www/html/vendor
      - ./backend/storage/logs:/var/www/html/storage/logs
    environment:
      APP_ENV: local
      APP_DEBUG: true
      APP_KEY: base64:9LHJB0goLJ1iZsCOqqsFwRoNfORasfX0W5146d9WHWA=
      APP_CIPHER: aes-256-cbc
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: bets
      DB_USERNAME: user
      DB_PASSWORD: pass
      SANCTUM_STATEFUL_DOMAINS: localhost:8081
      SESSION_DOMAIN: localhost
      SESSION_DRIVER: cookie
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: mysql:8
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bets
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./backend:/var/www/html:cached
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "8081:8081"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - app-network

volumes:
  db_data:
  vendor_data:

networks:
  app-network:
    driver: bridge
